### get
GET {{domain}}/test/txid
Content-Type: application/json
x-txid: test1234

### get
GET {{domain}}/test/error
Content-Type: application/json
x-txid: test1234

### request log
POST {{domain}}/test/requestlog?key=babamba
Content-Type: application/json
x-user-header: AAAA

{
  "id" : "webflux",
  "age": 30
}

### circuit breaker(Success)
GET {{domain}}/test/circuit
Content-Type: application/json

### circuit breaker(fail)
GET {{domain}}/test/circuit?flag=true
Content-Type: application/json