### get
GET {{domain}}/test/txid
Content-Type: application/json
x-txid: test1234

### get
GET {{domain}}/test/error
Content-Type: application/json
x-txid: test1234

### request log
POST {{domain}}/test/requestlog?key=babamba
Content-Type: application/json
x-user-header: AAAA

{
  "id" : "webflux",
  "age": 30
}