spring:
  application:
    name: mvc
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:////sample
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
server:
  shutdown: graceful
  compression:
    enabled: true
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true
logging:
  level:
    "dev.fastcampus.mvc": debug
  pattern:
    #    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid:-}|%green(%t)|%logger|%blue(\\(%F:%L\\))|%msg%n"
    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid:-}|%green(%t)|%blue(\\(%F:%L\\))|%msg%n"