version: "3.8"
services:
  webflux:
    container_name: webflux
    image: webflux:0.0.1-SNAPSHOT
    ports: #host -> contianer
      - "8080:8080"
    environment:
      - spring.r2dbc.url=r2dbc:pool:mariadb://192.168.129.188:3306/sample