CREATE TABLE IF NOT EXISTS TB_ARTICLE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    body VARCHAR(2000),
    author_id BIGINT,
    createdat TIMESTAMP,
    updatedat TIMESTAMP
);