version: "3.8"
services:
  mvc:
    container_name: mvc
    image: mvc:0.0.1-SNAPSHOT
    ports: #host -> contianer
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mariadb://192.168.129.188:3306/sample
