#spring:
#  profiles:
#    active: stress
#---
spring:
  application:
    name: webflux.coroutine
  output:
    ansi:
      enabled: always
  r2dbc:
#    url: r2dbc:pool:h2:mem://localhost/sample
    url: r2dbc:pool:h2:file:///./sample
  sql:
    init:
      mode: always
      schema-locations: classpath:script/schema.sql
server:
  shutdown: graceful
  compression:
    enabled: true
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid:-}|%green(%t)|%logger|%blue(\\(%F:%L\\))|%msg%n"
  level:
    "org.springframework.r2dbc.core": off
    "org.springframework.r2dbc.connection.init.ScriptUtils": off
    "dev.fastcampus.webflux": debug
    "io.r2dbc.h2.H2Connection": debug
    "org.springframework.boot.autoconfigure.web.reactive.error": off
    "org.springframework.web.HttpLogging": off
---
spring:
  config:
    activate:
      on-profile: stress
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:3306/sample
    username: user
    password: 1234