spring:
  profiles:
    active: stress
---
spring:
  application:
    name: webflux.coroutine
  output:
    ansi:
      enabled: always
  r2dbc:
    url: r2dbc:pool:h2:mem://localhost/sample
  sql:
    init:
      mode: always
      schema-locations: classpath:script/schema.sql
server:
  shutdown: graceful
  compression:
    enabled: true
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true
logging:
  level:
    "org.springframework.r2dbc.core": debug
    "org.springframework.r2dbc.connection.init.ScriptUtils": debug
    "dev.fastcampus.webflux": debug
    "io.r2dbc.h2.H2Connection": debug
---
spring:
  config:
    activate:
      on-profile: stress
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:3306/sample
    username: user
    password: 1234